server:
  port: 8082

spring:
  application:
    name: monew_batch
    version: 1.0.0
  profiles:
    active: local
  batch:
    job:
      enabled: false

article:
  naver:
    api:
      client-id: ${NAVER_API_CLIENT_ID}
      client-secret: ${NAVER_API_CLIENT_SECRET}
      base-url: https://openapi.naver.com/v1/search/news.json
  hankyung:
    api:
      base-url: https://www.hankyung.com/feed
  chosun:
    api:
      base-url: https://www.chosun.com/arc/outboundfeeds/rss/category
  yonhap:
    api:
      base-url: https://www.yonhapnewstv.co.kr/category/news

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  bucket: ${AWS_S3_BUCKET}

storage:
  type: s3

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    batch:
      enabled: true
  health:
    defaults:
      enabled: true
