spring:
  config:
    import: optional:dotenv:.
    activate:
      on-profile: local

  #  boot:
  #    admin:
  #      client:
  #        url: http://localhost:9090
  #        enabled: true
  #        instance:
  #          name: monew_batch
  #          service-url: http://localhost:8082
  #          management-base-url: http://localhost:8082

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  datasource-data:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:${DB_LOCAL_PORT:5432}/${DB_LOCAL_DB_NAME:monew}
    username: ${DB_LOCAL_USER:postgres}
    password: ${DB_LOCAL_PASSWORD:1234}

  datasource-meta:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:${DB_LOCAL_METADATA_PORT:5432}/${DB_LOCAL_METADATA_DB_NAME:monew_batch_metadata}
    username: ${DB_LOCAL_METADATA_USER:postgres}
    password: ${DB_LOCAL_METADATA_PASSWORD:1234}

logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
    org.hibernate.type.descriptor.sql: info
    org.springframework.web: info
    com.monew.monew_server: info